import type { CategoryInfo, Product } from "./types"

export const categories: CategoryInfo[] = [
  { value: "sarees", label: "Sarees", image: "/images/saree-studio-blue.jpg" },
  { value: "womens-wear", label: "Women's Wear", image: "/images/saree-portrait-pillar.jpg" },
  { value: "salwar-suits", label: "Salwar Suits", image: null },
  { value: "designer", label: "Designer", image: null },
  { value: "blouses", label: "Blouses", image: null },
  { value: "jewellery", label: "Jewellery", image: null },
  { value: "mens-wear", label: "Men's Wear", image: null },
  { value: "handbags", label: "Hand Bags", image: null },
  { value: "petticoats", label: "Petticoats", image: null },
]

// Sample seed data — replaced by Supabase content in phase 2.
// Category imagery gap: only sarees/women's-wear have real photography today
// (all 6 licensed photos are saree lifestyle shots). Other categories use
// "/placeholder.svg" until real product photos are supplied.
export const products: Product[] = [
  {
    id: "royal-banarasi-silk",
    createdAt: "2026-06-05T12:00:00.000Z",
    code: "SL001",
    name: "Royal Banarasi Silk Saree",
    tagline: "Regal silver zari on deep royal blue",
    description: "A handwoven Banarasi silk saree with intricate silver zari work, draped in a rich studio setting that shows off its fall and sheen.",
    price: 4999,
    mrp: 6999,
    images: ["/images/saree-studio-blue.jpg"],
    category: "sarees",
    collection: "silk",
    properties: { fabric: "Pure Silk", work: "Zari Weaving", blouseIncluded: true, washCare: "Dry Clean Only", occasion: "Wedding & Festive", color: "Royal Blue" },
    stock: 12,
    codAvailable: true,
    estimatedDeliveryDays: [4, 7],
    boughtCount: 18,
  },
  {
    id: "heritage-kanjivaram",
    createdAt: "2026-07-18T12:00:00.000Z",
    code: "SL002",
    name: "Heritage Kanjivaram Silk Saree",
    tagline: "Temple-border weave with a story",
    description: "A classic Kanjivaram silk saree in magenta and gold zari, woven near a heritage stone wall — timeless elegance for festive occasions.",
    price: 6499,
    mrp: null,
    images: ["/images/saree-heritage-wall.jpg"],
    category: "sarees",
    collection: "kanjivaram-silk",
    properties: { fabric: "Kanjivaram Silk", work: "Temple Border Zari", blouseIncluded: true, washCare: "Dry Clean Only", occasion: "Wedding", color: "Magenta & Gold" },
    stock: 8,
    codAvailable: true,
    estimatedDeliveryDays: [5, 8],
    boughtCount: 9,
  },
  {
    id: "cream-gold-drape",
    createdAt: "2026-05-29T12:00:00.000Z",
    code: "SC001",
    name: "Cream & Gold Handloom Saree",
    tagline: "Soft drape, quiet luxury",
    description: "A cream and gold handloom saree with a delicate red blouse pairing, styled with jhumka earrings for an understated festive look.",
    price: 2499,
    mrp: 2999,
    images: ["/images/saree-portrait-earring.jpg"],
    category: "sarees",
    collection: "silk-cotton",
    properties: { fabric: "Handloom Cotton Silk", work: "Zari Border", blouseIncluded: true, washCare: "Dry Clean Only", occasion: "Festive", color: "Cream & Gold" },
    stock: 15,
    codAvailable: true,
    estimatedDeliveryDays: [4, 7],
  },
  {
    id: "magenta-pillar-silk",
    createdAt: "2026-05-22T12:00:00.000Z",
    code: "SL003",
    name: "Magenta Pillar Silk Saree",
    tagline: "Jasmine, gold, and grace",
    description: "A magenta silk saree with a hot-pink blouse and fresh jasmine hair adornment — a rich, photogenic pick for celebrations.",
    price: 3299,
    mrp: null,
    images: ["/images/saree-portrait-pillar.jpg"],
    category: "sarees",
    collection: "silk",
    properties: { fabric: "Silk", work: "Zari Border", blouseIncluded: true, washCare: "Dry Clean Only", occasion: "Festive", color: "Magenta" },
    stock: 10,
    codAvailable: true,
    estimatedDeliveryDays: [4, 7],
  },
  {
    id: "banarasi-duo-collection",
    createdAt: "2026-05-15T12:00:00.000Z",
    code: "SL004",
    name: "Banarasi Duo Collection Saree",
    tagline: "Editorial richness, everyday elegance",
    description: "Part of a curated Banarasi-style collection in red and pink, photographed against a heritage wall for a true sense of texture and drape.",
    price: 5499,
    mrp: 6999,
    images: ["/images/saree-duo-editorial.jpg"],
    category: "sarees",
    collection: "banaras",
    properties: { fabric: "Banarasi Silk", work: "Woven Zari", blouseIncluded: true, washCare: "Dry Clean Only", occasion: "Wedding & Festive", color: "Red & Pink" },
    stock: 6,
    codAvailable: true,
    estimatedDeliveryDays: [5, 8],
  },
  {
    id: "garden-chiffon-saree",
    createdAt: "2026-07-15T12:00:00.000Z",
    code: "SR001",
    name: "Garden Breeze Chiffon Saree",
    tagline: "Light as air, effortless to drape",
    description: "A flowing maroon chiffon saree with a fluttering pallu, perfect for daytime events and easy everyday elegance.",
    price: 2899,
    mrp: null,
    images: ["/images/saree-garden-breeze.jpg"],
    category: "sarees",
    properties: { fabric: "Chiffon", work: "Lace Border", blouseIncluded: true, washCare: "Hand Wash Cold", occasion: "Daywear", color: "Maroon" },
    stock: 14,
    codAvailable: true,
    estimatedDeliveryDays: [3, 6],
  },
  {
    id: "vintage-kanjivaram-saree",
    createdAt: "2026-07-12T12:00:00.000Z",
    code: "SL005",
    name: "Vintage Kanjivaram Saree",
    tagline: "Warm tones, old-world charm",
    description: "A yellow and red Kanjivaram silk saree with a vintage colour grade, styled simply on a wooden chair to let the weave speak for itself.",
    price: 5299,
    mrp: null,
    images: ["/images/saree-vintage-kanjivaram.jpg"],
    category: "sarees",
    collection: "kanjivaram-silk",
    properties: { fabric: "Kanjivaram Silk", work: "Zari Border", blouseIncluded: true, washCare: "Dry Clean Only", occasion: "Wedding & Festive", color: "Yellow & Red" },
    stock: 7,
    codAvailable: true,
    estimatedDeliveryDays: [5, 8],
  },
  {
    id: "pastel-drape-saree",
    createdAt: "2026-05-08T12:00:00.000Z",
    code: "SL006",
    name: "Pastel Drape Silk Saree",
    tagline: "Soft hues, editorial elegance",
    description: "A green silk saree styled with flowing pastel pink and orange sheer fabric, gold jhumkas finishing the look.",
    price: 3799,
    mrp: null,
    images: ["/images/saree-pastel-drapes.jpg"],
    category: "sarees",
    collection: "silk",
    properties: { fabric: "Silk", work: "Zari Border", blouseIncluded: true, washCare: "Dry Clean Only", occasion: "Festive", color: "Green" },
    stock: 9,
    codAvailable: true,
    estimatedDeliveryDays: [4, 7],
  },
  {
    id: "golden-hour-silk-saree",
    createdAt: "2026-05-01T12:00:00.000Z",
    code: "SL007",
    name: "Golden Hour Silk Saree",
    tagline: "Warm light, timeless silk",
    description: "A green and gold silk saree photographed by a brass lamp with scattered jasmine flowers — rich colour that photographs beautifully for every celebration.",
    price: 4199,
    mrp: 4799,
    images: ["/images/saree-brass-lamp.jpg", "/images/saree-candid-jasmine.jpg"],
    category: "sarees",
    collection: "silk",
    properties: { fabric: "Silk", work: "Zari Border", blouseIncluded: true, washCare: "Dry Clean Only", occasion: "Festive", color: "Green & Gold" },
    stock: 11,
    codAvailable: true,
    estimatedDeliveryDays: [4, 7],
  },
  {
    id: "heritage-walk-saree",
    createdAt: "2026-04-24T12:00:00.000Z",
    code: "SL008",
    name: "Heritage Walk Silk Saree",
    tagline: "Grace within temple corridors",
    description: "A red and multicolour silk saree captured within a grand temple corridor, golden light catching every fold of the drape.",
    price: 4599,
    mrp: null,
    images: ["/images/saree-temple-corridor.jpg"],
    category: "sarees",
    collection: "silk",
    properties: { fabric: "Silk", work: "Zari Border", blouseIncluded: true, washCare: "Dry Clean Only", occasion: "Wedding & Festive", color: "Red & Multicolour" },
    stock: 8,
    codAvailable: true,
    estimatedDeliveryDays: [5, 8],
  },

  {
    id: "anarkali-evening-dress",
    createdAt: "2026-07-09T12:00:00.000Z",
    code: "WW001",
    name: "Anarkali Evening Dress",
    tagline: "Flowing silhouette, festive detailing",
    description: "A floor-length Anarkali dress with delicate embroidery, designed for evening functions and celebrations.",
    price: 3499,
    mrp: 3999,
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    category: "womens-wear",
    properties: { fabric: "Georgette", work: "Embroidery", washCare: "Dry Clean Only", occasion: "Festive", color: "Emerald Green" },
    sizes: ["S", "M", "L", "XL"],
    sizeStock: { S: 3, M: 4, L: 2, XL: 0 },
    stock: 9,
    codAvailable: true,
    estimatedDeliveryDays: [5, 8],
    boughtCount: 6,
  },
  {
    id: "indo-western-gown",
    createdAt: "2026-04-17T12:00:00.000Z",
    code: "WW002",
    name: "Indo-Western Gown",
    tagline: "Contemporary cut, ethnic soul",
    description: "A fusion gown blending Indian embroidery with a modern silhouette — a versatile pick for receptions and parties.",
    price: 4299,
    mrp: null,
    images: ["/placeholder.svg"],
    category: "womens-wear",
    properties: { fabric: "Satin Georgette", work: "Sequin Embroidery", washCare: "Dry Clean Only", occasion: "Party & Reception", color: "Wine Red" },
    sizes: ["S", "M", "L", "XL"],
    stock: 7,
    codAvailable: true,
    estimatedDeliveryDays: [5, 9],
  },

  {
    id: "designer-readymade-blouse",
    createdAt: "2026-04-10T12:00:00.000Z",
    code: "BL001",
    name: "Designer Readymade Blouse",
    tagline: "Pair-perfect with any silk saree",
    description: "A readymade designer blouse with statement sleeves and back detailing, cut for a comfortable, flattering fit.",
    price: 899,
    mrp: 1099,
    images: ["/placeholder.svg"],
    category: "blouses",
    properties: { fabric: "Silk Blend", work: "Embroidered Yoke", washCare: "Dry Clean Only", occasion: "Festive", color: "Gold" },
    sizes: ["32", "34", "36", "38", "40"],
    stock: 20,
    codAvailable: true,
    estimatedDeliveryDays: [3, 6],
  },
  {
    id: "embroidered-silk-blouse",
    createdAt: "2026-04-03T12:00:00.000Z",
    code: "BL002",
    name: "Embroidered Silk Blouse",
    tagline: "Handworked detailing, timeless fit",
    description: "A rich silk blouse with hand embroidery along the neckline, made to pair beautifully with Kanjivaram and Banarasi sarees.",
    price: 1199,
    mrp: null,
    images: ["/placeholder.svg"],
    category: "blouses",
    properties: { fabric: "Pure Silk", work: "Hand Embroidery", washCare: "Dry Clean Only", occasion: "Wedding", color: "Maroon" },
    sizes: ["32", "34", "36", "38", "40"],
    stock: 16,
    codAvailable: true,
    estimatedDeliveryDays: [4, 7],
  },

  {
    id: "kundan-necklace-set",
    createdAt: "2026-03-27T12:00:00.000Z",
    code: "JW001",
    name: "Kundan Necklace Set",
    tagline: "Bridal-ready statement piece",
    description: "A Kundan-studded necklace set with matching earrings, designed to be the centerpiece of any festive or bridal look.",
    price: 2499,
    mrp: 2999,
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    category: "jewellery",
    properties: { work: "Kundan & Pearl", occasion: "Wedding & Festive", color: "Gold" },
    stock: 10,
    codAvailable: true,
    estimatedDeliveryDays: [3, 6],
    boughtCount: 15,
  },
  {
    id: "temple-jhumka-earrings",
    createdAt: "2026-03-20T12:00:00.000Z",
    code: "JW002",
    name: "Temple Jhumka Earrings",
    tagline: "Classic gold-tone temple work",
    description: "Lightweight temple-style jhumka earrings with a gold-tone finish, an everyday festive essential.",
    price: 999,
    mrp: null,
    images: ["/placeholder.svg"],
    category: "jewellery",
    properties: { work: "Temple Jewellery", occasion: "Festive & Daily Wear", color: "Gold" },
    stock: 25,
    codAvailable: true,
    estimatedDeliveryDays: [2, 5],
  },

  {
    id: "mens-kurta-set",
    createdAt: "2026-03-13T12:00:00.000Z",
    code: "MW001",
    name: "Men's Silk Kurta Set",
    tagline: "Festive-ready in two pieces",
    description: "A classic kurta and pyjama set in raw silk, tailored for a comfortable festive fit.",
    price: 1799,
    mrp: 2199,
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    category: "mens-wear",
    properties: { fabric: "Raw Silk", washCare: "Dry Clean Only", occasion: "Festive", color: "Cream" },
    sizes: ["M", "L", "XL", "XXL"],
    sizeStock: { M: 5, L: 6, XL: 4, XXL: 0 },
    stock: 18,
    codAvailable: true,
    estimatedDeliveryDays: [4, 7],
    boughtCount: 11,
  },
  {
    id: "mens-nehru-jacket",
    createdAt: "2026-07-06T12:00:00.000Z",
    code: "MW002",
    name: "Men's Nehru Jacket",
    tagline: "Sharp layering for any occasion",
    description: "A tailored Nehru jacket that layers effortlessly over kurtas for weddings and festive gatherings.",
    price: 2299,
    mrp: null,
    images: ["/placeholder.svg"],
    category: "mens-wear",
    properties: { fabric: "Jacquard", washCare: "Dry Clean Only", occasion: "Wedding & Festive", color: "Maroon" },
    sizes: ["M", "L", "XL", "XXL"],
    stock: 11,
    codAvailable: true,
    estimatedDeliveryDays: [4, 8],
  },
  {
    id: "mens-silk-dhoti",
    createdAt: "2026-03-06T12:00:00.000Z",
    code: "MW003",
    name: "Men's Silk Dhoti",
    tagline: "Traditional drape, festive gold border",
    description: "A pure silk dhoti with a woven gold border, ready to drape for weddings and religious occasions.",
    price: 1299,
    mrp: null,
    images: ["/placeholder.svg"],
    category: "mens-wear",
    properties: { fabric: "Pure Silk", work: "Zari Border", washCare: "Dry Clean Only", occasion: "Wedding & Religious", color: "Cream & Gold" },
    stock: 14,
    codAvailable: true,
    estimatedDeliveryDays: [4, 7],
  },

  {
    id: "embroidered-potli-bag",
    createdAt: "2026-02-27T12:00:00.000Z",
    code: "HB001",
    name: "Embroidered Potli Bag",
    tagline: "A handheld finishing touch",
    description: "A hand-embroidered potli bag with a drawstring closure, sized to carry the essentials for any festive outing.",
    price: 799,
    mrp: 999,
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    category: "handbags",
    properties: { material: "Silk Brocade", work: "Hand Embroidery", occasion: "Festive & Wedding", color: "Maroon & Gold" },
    stock: 22,
    codAvailable: true,
    estimatedDeliveryDays: [3, 6],
    boughtCount: 8,
  },
  {
    id: "ethnic-clutch",
    createdAt: "2026-02-20T12:00:00.000Z",
    code: "HB002",
    name: "Ethnic Embellished Clutch",
    tagline: "Compact, festive, versatile",
    description: "A structured clutch with embellished detailing, designed to complement both sarees and Indo-western outfits.",
    price: 1099,
    mrp: null,
    images: ["/placeholder.svg"],
    category: "handbags",
    properties: { material: "Satin", work: "Stone Embellishment", occasion: "Party & Festive", color: "Emerald Green" },
    stock: 13,
    codAvailable: true,
    estimatedDeliveryDays: [3, 6],
  },

  {
    id: "cotton-saree-petticoat",
    createdAt: "2026-02-13T12:00:00.000Z",
    code: "PC001",
    name: "Cotton Saree Petticoat",
    tagline: "Everyday comfort under any drape",
    description: "A breathable cotton petticoat with an adjustable drawstring waist, made to support daily-wear sarees comfortably.",
    price: 399,
    mrp: 499,
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    category: "petticoats",
    properties: { fabric: "Cotton", washCare: "Machine Wash", color: "Off-White" },
    sizes: ["S", "M", "L", "XL", "XXL"],
    sizeStock: { S: 8, M: 10, L: 7, XL: 5, XXL: 0 },
    stock: 30,
    codAvailable: true,
    estimatedDeliveryDays: [2, 5],
    boughtCount: 22,
  },
  {
    id: "satin-shapewear-petticoat",
    createdAt: "2026-07-03T12:00:00.000Z",
    code: "PC002",
    name: "Satin Shapewear Petticoat",
    tagline: "A smooth base for silk sarees",
    description: "A satin shapewear petticoat designed to give silk and georgette sarees a smooth, clean fall.",
    price: 599,
    mrp: null,
    images: ["/placeholder.svg"],
    category: "petticoats",
    properties: { fabric: "Satin", washCare: "Hand Wash Cold", color: "Black" },
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 20,
    codAvailable: true,
    estimatedDeliveryDays: [2, 5],
  },

  {
    id: "anarkali-salwar-suit",
    createdAt: "2026-06-30T12:00:00.000Z",
    code: "SS001",
    name: "Anarkali Salwar Suit Set",
    tagline: "Flowing silhouette, everyday grace",
    description: "A 3-piece unstitched salwar suit set with a floor-length Anarkali kameez, matching salwar, and dupatta.",
    price: 2799,
    mrp: 3299,
    images: ["/placeholder.svg", "/placeholder.svg"],
    category: "salwar-suits",
    properties: { fabric: "Cotton Silk", work: "Thread Embroidery", washCare: "Dry Clean Only", occasion: "Festive & Daily Wear", color: "Teal" },
    sizes: ["S", "M", "L", "XL"],
    sizeStock: { S: 4, M: 6, L: 5, XL: 2 },
    stock: 17,
    codAvailable: true,
    estimatedDeliveryDays: [4, 7],
    boughtCount: 7,
  },
  {
    id: "printed-straight-suit",
    createdAt: "2026-02-06T12:00:00.000Z",
    code: "SS002",
    name: "Printed Straight-Cut Suit Set",
    tagline: "Everyday elegance, effortless print",
    description: "A straight-cut cotton salwar suit set with a block-print kameez, palazzo, and matching dupatta — comfortable daily wear with festive polish.",
    price: 1899,
    mrp: null,
    images: ["/placeholder.svg"],
    category: "salwar-suits",
    properties: { fabric: "Cotton", work: "Block Print", washCare: "Machine Wash", occasion: "Daywear", color: "Indigo" },
    sizes: ["S", "M", "L", "XL", "XXL"],
    sizeStock: { S: 6, M: 8, L: 6, XL: 4, XXL: 2 },
    stock: 26,
    codAvailable: true,
    estimatedDeliveryDays: [3, 6],
    boughtCount: 5,
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products
  return products.filter((p) => p.category === category)
}
